FROM redis:latest
# COPY ./config/redis.conf /usr/local/etc/redis/redis.conf
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]


# -------------- commands ---------------
# docker exec -it redis bash  
# $ redis-cli
#   127.0.0.1:6379> ping
    # PONG

